image: "node:16.4.0"


deployment:
  before_script:
    - apt update -qq && apt install -y -qq rsync
  script:
    - npm install -g hexo-cli
    - npm install
    - hexo generate
    - rsync public/ /var/www/html -avr
